-- MySQL Script generated by MySQL Workbench
-- Wed Aug  5 17:02:58 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ottcommunity
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ottcommunity
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ottcommunity` DEFAULT CHARACTER SET utf8 ;
USE `ottcommunity` ;

-- -----------------------------------------------------
-- Table `ottcommunity`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ottcommunity`.`user` (
  `id` INT(11) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `active` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;